import React from "react";
import { useNavigate } from "react-router-dom";
import Layout from "./Layout";

const FlightOwnerPage = () => {
  const navigate = useNavigate();

  return (
    <Layout>
      <div className="container mt-4">
        <h2 className="text-center mb-4">✈️ Flight Owner Dashboard</h2>
        <p className="text-center mb-5">
          Welcome, Flight Owner! You can manage flights, view bookings, and monitor your revenue from here.
        </p>

        <div className="row justify-content-center">
          <div className="col-md-4 mb-3">
            <div className="card shadow p-4 text-center">
              <h5 className="mb-3">🛫 Manage Flights</h5>
              <p>Add, edit, or delete your flight listings.</p>
              <button
                className="btn btn-primary w-100"
                onClick={() => navigate("/flight-owner/manage-flights")}
              >
                Go
              </button>
            </div>
          </div>

          <div className="col-md-4 mb-3">
            <div className="card shadow p-4 text-center">
              <h5 className="mb-3">📋 View Bookings</h5>
              <p>Review bookings made by passengers for your flights.</p>
              <button
                className="btn btn-success w-100"
                onClick={() => navigate("/flight-owner/bookings")}
              >
                View Bookings
              </button>
            </div>
          </div>

          {/* <div className="col-md-4 mb-3">
            <div className="card shadow p-4 text-center">
              <h5 className="mb-3">💰 Track Earnings</h5>
              <p>Check revenue generated by your flights.</p>
              <button
                className="btn btn-warning w-100"
                onClick={() => navigate("/flight-owner/earnings")}
              >
                Track Earnings
              </button>
            </div>
          </div> */}
        </div>
      </div>
    </Layout>
  );
};

export default FlightOwnerPage;
